### PR TITLE
fix for write_multiple_coils

### PR DESCRIPTION
**Pull request by giampiero7**
number of bytes was wrong when writing a multiple of 8 outputs

### CODE REVIEW

**Comment by giampiero7** [comment]
Hi,
I'm working on the development of the libraries for our soon-to-be-released product _iono pycom_.
Similar to [this one](https://www.sferalabs.cc/iono-arduino/), but based on pycom, rather than Arduino.
I'm soon going to develop a library to use the module as a Modbus slave and, if it's OK with you, I'd be happy to add this functionalities to your base library too.
In case, would you prefer creating a new branch where I can push to?

Cheers!

Giampiero

**Comment by danicampora** [comment]
Merged here: https://github.com/pycom/pycom-modbus.

Thanks!!

**Comment by giampiero7** [comment]
Thanks @danicampora ! Let me know if you'd be interested in integrating the Modbus slave functionalities and how you'd like to manage the repo...

**Comment by danicampora** [comment]
@giampiero7 yes, please do submit a pull request for the salve functionalities. That sound very interesting! We are open to contributions all the time, the more the better :-)

**Pull request closed without merging**
